### ISSUE TITLE
credhub find allows extra arguments

### ISSUE THREAD

**Issue by poy** [cloudfoundry-incubator/credhub-cli#41] opened 2018-04-03 15:52 UTC
What version of the credhub server you are using?
```
Server Version: 1.7.2
```

What version of the credhub cli you are using?
```
CLI Version: 1.7.0    
```

If you were attempting to accomplish a task, what was it you were attempting to do?

Use the `find` subcommand with an extra argument:

```
credhub find /some/key
```

Notice I did not provide a `-n` flag.

What did you expect to happen?

Return an error

What was the actual behavior?

It ignored the extra argument and returned everything.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by mdelillo** [comment] 2018-10-01 19:03
@apoydence thanks for reporting this, we'll prioritize as necessary.

**Comment by martys34** [comment] 2018-10-18 22:04
@apoydence The issue is now fixed. It will be out in the next CLI version.

**Comment by ankeesler** [comment] 2019-04-29 18:59
Closing as this is now fixed. @poy, please let us know if the error still exists.

**Closed by ankeesler** 2019-04-29 18:59 UTC
Labels: accepted
