### ISSUE TITLE
Regenerating a statically set credential should return an error

### ISSUE THREAD

**Issue by aboik** [cloudfoundry-incubator/credhub-cli#35] opened 2018-02-23 18:19 UTC
What version of the credhub server you are using?
1.3.4

What version of the credhub cli you are using?
1.5.0

If you were attempting to accomplish a task, what was it you were attempting to do?
Regenerate a statically set credential

What did you expect to happen?
Expected to receive an error with the command returning non-zero exit code.

What was the actual behavior?
Command printed blank line and returned with exit code 0.

With CredHub server v1.3.4, calling the regenerate API on a statically set credential returns this error:
`The user could not be regenerated because the value was statically set. Only generated users may be regenerated.`

Using the `credhub regenerate` command from CredHub CLI v1.5.0 on the same credential returns no error. Executing `credhub find` on the credential afterward shows that the credential has not been updated.

Steps to reproduce:
```
$ date
Fri Feb 23 13:12:45 EST 2018
$ credhub regenerate -n "/p-bosh/cf-aa8ac10268039ab9c5f7/autoscale-db-credentials"

$ echo $?
0
$ credhub find -n "/p-bosh/cf-aa8ac10268039ab9c5f7/autoscale-db-credentials"
credentials:
- name: /p-bosh/cf-aa8ac10268039ab9c5f7/autoscale-db-credentials
  version_created_at: 2018-01-07T23:41:38Z
```

Please confirm where necessary:
* [X] I have included a log output
* [ ] My log includes an error message
* [X] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by ebeer** [comment] 2018-02-23 20:36
@aboik what is the credential type that you experienced this behavior with?

**Comment by aboik** [comment] 2018-02-23 21:18
The statically set credentials all happened to be _user_ credentials.

**Comment by molambo** [comment] 2018-03-05 15:05
Hey @aboik, we were able to reproduce this issue with cli version 1.5.0. It looks like the issue was fixed in [this commit](https://github.com/cloudfoundry-incubator/credhub-cli/commit/366ab86a5d0e669be8c5c5512c4025d98e8f13ba). Any version 1.5.1 and later this issue should be fixed.

Closing this issue. Please reopen if you have any other concerns.

**Closed by molambo** 2018-03-05 15:05 UTC
Labels: in progress
