### ISSUE TITLE
Import fails with block indentation indicator

### ISSUE THREAD

**Issue by crdant** [cloudfoundry-incubator/credhub-cli#59] opened 2018-09-25 15:48 UTC
What version of the credhub server you are using?

CLI only issue

What version of the credhub cli you are using?

1.7.5

If you were attempting to accomplish a task, what was it you were attempting to do?

Import a YAML file with [block-indentation indicators](http://yaml.org/spec/current.html#id2538125), e.g.

```
credentials:
- name: /concourse/pivotal_cloud_foundry/deploy-harbor/server_certificate
  type: certificate
  value:
    certificate: |6
          -----BEGIN CERTIFICATE-----
          MIIGGTCCBQGgAwIBAgISA0p5evMPElOBFaUPSJtg1B7hMA0GCSqGSIb3DQEBCwUA
          MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
          ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xODA5MjEyMDEwNDFaFw0x
          ODEyMjAyMDEwNDFaMCIxIDAeBgNVBAMTF3JlZ2lzdHJ5LnBjZi5jcmRhbnQubmV0
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAov8eaICIUNfk/Fqc1pfh
          wTdshILqGxBciHcPeeeGoBI4GtB3fLD+0jrrtTMe4jroBzlEc7oPg1Xvq/V1m3En
          HDxUkF88lj4iV7Sy0VSz1AYDl/fdrW6iIbtWjVqiBetICOo5PA8pm94y1UCPeL3T
          N2vwm9L/RVn6LPSV+AUAVAw2uzzXiT6wi/D4W58h9SysKH60uyLvw7lqyfLfgJzi
          rhmjkA8T/nubm87jaf27Cx5BpG2+OwMUHFZh7QX07xSAkk5g8RlZ1DiOjB9DA4dU
          oGeHqENvfQWsH3FnTNHpzlJ5kpTKLt6R5RuaxhG6THkD2rPMPu6Osgiico4mbVz6
          vwIDAQABo4IDHzCCAxswDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUF
          BwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRoWQK17/n0Zj1I
          9Ey+egNEBW/1ozAfBgNVHSMEGDAWgBSoSmpjBH3duubRObemRWXv86jsoTBvBggr
          BgEFBQcBAQRjMGEwLgYIKwYBBQUHMAGGImh0dHA6Ly9vY3NwLmludC14My5sZXRz
          ZW5jcnlwdC5vcmcwLwYIKwYBBQUHMAKGI2h0dHA6Ly9jZXJ0LmludC14My5sZXRz
          ZW5jcnlwdC5vcmcvMCIGA1UdEQQbMBmCF3JlZ2lzdHJ5LnBjZi5jcmRhbnQubmV0
          MIH+BgNVHSAEgfYwgfMwCAYGZ4EMAQIBMIHmBgsrBgEEAYLfEwEBATCB1jAmBggr
          BgEFBQcCARYaaHR0cDovL2Nwcy5sZXRzZW5jcnlwdC5vcmcwgasGCCsGAQUFBwIC
          MIGeDIGbVGhpcyBDZXJ0aWZpY2F0ZSBtYXkgb25seSBiZSByZWxpZWQgdXBvbiBi
          eSBSZWx5aW5nIFBhcnRpZXMgYW5kIG9ubHkgaW4gYWNjb3JkYW5jZSB3aXRoIHRo
          ZSBDZXJ0aWZpY2F0ZSBQb2xpY3kgZm91bmQgYXQgaHR0cHM6Ly9sZXRzZW5jcnlw
          dC5vcmcvcmVwb3NpdG9yeS8wggEEBgorBgEEAdZ5AgQCBIH1BIHyAPAAdQBvU3as
          MfAxGdiZAKRRFf93FRwR2QLBACkGjbIImjfZEwAAAWX9+G2gAAAEAwBGMEQCICZY
          fJBtkd/9bYP3jTf7NeWY1Jwhi0UPPZMXQHLEMBtPAiBrsDkwwC70NBC4qoyG9bXO
          Utm+CfjNeRaxn7rP2/jawgB3AKRQEmkFWhVUXmIRqze8ED9irlV2pF5LFxRFPhsi
          EGolAAABZf34bVgAAAQDAEgwRgIhAIfY6IHHGKjr0Amc5DU2HPGd4OjMrDypSUGN
          35oL9FU3AiEA8sL4PYhtcdqkRRg4KlPCtIpAXOx2dQXS54TQo085cJwwDQYJKoZI
          hvcNAQELBQADggEBAAKI+OvFYFCW+Yjwi/9CtRSaqhp4S5U+Gv67zk02oueuY4k0
          VVoZGXudaWhba2UaSN6CkAPXSeSjlH/1Oi+5h8rKD5Mys44l9YrF9o/7IiqzHrZr
          9Nheu76O4Ma7AsFEVNg+h6QfNV57fCTEKEP62PzcYs9hV94sFW8dSi9acS4IpIBS
          2/Hq/ssjuCnZo4RrgslY9bhknwWLwI5FBcnwM7OPm5mmwZv5LyVgVJfz+6HqpgXk
          5XB7AobyXUrAS3HKXx7vPl2ARRabotDBxwyM6vELtHolZsSFObANun9a1WJEl0Og
          OWuJbVVRWTfhySd1nlxcb+3EpfifczZXAmW9a7w=
          -----END CERTIFICATE-----
```

What did you expect to happen?

The YAML file to be imported.

What was the actual behavior?

`The referenced file does not contain valid yaml structure. Please update and retry your request.`

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ X] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by athornton2012** [comment] 2018-10-01 16:13
@crdant It looks like you have tabs in your indentation. We tried to reproduce, but it all worked fine. When we added a tab in one of the indented lines then we saw the error. Closing

**Closed by athornton2012** 2018-10-01 16:13 UTC
Labels: unscheduled
